### ISSUE TITLE
Disable http

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/prototype-city-pairs-api#29]
Currently this is redirecting HTTP requests to HTTPS using a HTTP 307 "Internal redirect". However, the CIO HTTPS standards for APIs recommend returning a 403 forbidden. (Email sent to cloud.gov support.)

https://https.cio.gov/apis/

**Comment by Ryandaydev** [comment]
According to cloud.gov support this behavior is configured at the platform level and is not customizable. They suggest  mitigating this by advertising the HTTPS URLs and discouraging HTTP requests. 

We need to update the technical notes and documentation to address this.

**Comment by mogul** [comment]
To be absolutely clear, the `307 Internal redirect` is because cloud.gov is in the [HSTS preload list](https://hstspreload.org/) along with many other .gov sites. This list basically tells browsers and other clients "never, ever connect to URLs on this domain without TLS; opt for the `https://` version instead, even if someone entered `http://`". This is a best-practice for securing web interactions because there is absolutely zero chance that an attacker can intercept or tamper with the initial request from the client to the server over `http://`. Even if we were not in the HSTS list for a given client, our config would cause the browser to retry over `https://` after its first connection.

The CIO HTTPS standards recommend a `403 Forbidden` but the way we're set up clients are not in fact accessing your API over `http://` at any time.

**Comment by konklone** [comment]
So it's clear, https://https.cio.gov/apis/ is just best practice suggestions. Only https://https.cio.gov and https://https.cio.gov/guide/ are requirements or policy. (I manage the site.)

Also -

* 307 Internal redirects will only be performed by clients which support the HSTS preload list, which are more or less only browsers. API clients are unlikely to respect HSTS or the preload list, and so they will get the response that is sent by the server. 
* The guidance recommends 403s because they promote clearer client behavior, and avoid clients relying on redirect activity. Clients may or may not follow redirects -- clients will have no choice but to deal with content-less 403s. However, this may not be a big deal, and it's also less of a big deal for new APIs that aren't migrating legacy clients over.
* Browsers that do respect HSTS also have consistent redirect behavior, and so are not the target clients for the 403 recommendation.

The short of it is, cloud.gov's behavior is fine, and I'd welcome some suggestions or a PR to https.cio.gov (the content is at https://github.com/GSA/https/blob/master/pages/apis.md) to make this more clear.

**Comment by mogul** [comment]
> API clients are unlikely to respect HSTS or the preload list, and so they will get the response that is sent by the server.

In this case, API clients will hit the proxy at port 80 for everything hosted on cloud.gov, which simply returns a `301 Moved Permanently` with the same URL, where `https://` replaces `http://`.

**Comment by Ryandaydev** [comment]
Thanks for the detailed follow up. I confirmed that the API returns `301 Moved Permanently` when executed with a proper API client.
